version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      androidx:
        patterns:
          - "androidx.*"
      kotlin-and-gradle:
        patterns:
          - "org.jetbrains.kotlin*"
          - "com.android.tools.build:gradle"
          - "com.google.devtools.ksp*"
